// Generated by scripts/sync-gallery.mjs — do not edit by hand.
export type GalleryPhoto = {
  src: string
  alt: string
  width: number
  height: number
}

export const HACKATHON_GALLERY_PHOTOS = [
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-0giz1vb7d-DSC_7834.jpg", alt: "Cursor Kigali Hackathon — DSC 7834", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-0wbdhhgfj-DSC_7756.jpg", alt: "Cursor Kigali Hackathon — DSC 7756", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-26bh7kk17-DSC_7826.jpg", alt: "Cursor Kigali Hackathon — DSC 7826", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-1ia5wzkrr-DSC_7840.jpg", alt: "Cursor Kigali Hackathon — DSC 7840", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-8vn9ov3lf-DSC_7835.jpg", alt: "Cursor Kigali Hackathon — DSC 7835", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-nmlv7lfl2-DSC_7838.jpg", alt: "Cursor Kigali Hackathon — DSC 7838", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-pjda1joa7-DSC_7749.jpg", alt: "Cursor Kigali Hackathon — DSC 7749", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-sroy286rn-DSC_7766.jpg", alt: "Cursor Kigali Hackathon — DSC 7766", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-fzi5bx3z2-DSC_7828_1.jpg", alt: "Cursor Kigali Hackathon — DSC 7828 1", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-fg8rbzqfd-DSC_7832_1.jpg", alt: "Cursor Kigali Hackathon — DSC 7832 1", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-6ay15xx49-DSC_7816.jpg", alt: "Cursor Kigali Hackathon — DSC 7816", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-1t5idmj01-DSC_7829.jpg", alt: "Cursor Kigali Hackathon — DSC 7829", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-6itagzx77-DSC_7826_1.jpg", alt: "Cursor Kigali Hackathon — DSC 7826 1", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-9308sxu8j-DSC_7799.jpg", alt: "Cursor Kigali Hackathon — DSC 7799", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-fwbd5j2fy-DSC_7821.jpg", alt: "Cursor Kigali Hackathon — DSC 7821", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-p7cw7bfyf-DSC_7819.jpg", alt: "Cursor Kigali Hackathon — DSC 7819", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-mimz4dw9y-DSC_7841.jpg", alt: "Cursor Kigali Hackathon — DSC 7841", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-6a0k6lmgy-DSC_7836.jpg", alt: "Cursor Kigali Hackathon — DSC 7836", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-ezrvqczi7-DSC_7774.jpg", alt: "Cursor Kigali Hackathon — DSC 7774", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-nmtjf0kaw-DSC_7787.jpg", alt: "Cursor Kigali Hackathon — DSC 7787", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-5qv19khd8-DSC_7824.jpg", alt: "Cursor Kigali Hackathon — DSC 7824", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-e8xv7efw2-DSC_7812.jpg", alt: "Cursor Kigali Hackathon — DSC 7812", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-t6005cf5h-DSC_7783.jpg", alt: "Cursor Kigali Hackathon — DSC 7783", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-2x81yfebz-DSC_7742.jpg", alt: "Cursor Kigali Hackathon — DSC 7742", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-qms7xadc4-DSC_7820.jpg", alt: "Cursor Kigali Hackathon — DSC 7820", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-21u2sp5as-DSC_7828.jpg", alt: "Cursor Kigali Hackathon — DSC 7828", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-gykmyou99-DSC_7827.jpg", alt: "Cursor Kigali Hackathon — DSC 7827", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-7qqqiq7pu-DSC_7830.jpg", alt: "Cursor Kigali Hackathon — DSC 7830", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-4mba818o1-DSC_7728.jpg", alt: "Cursor Kigali Hackathon — DSC 7728", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-xzj9qai17-DSC_7832.jpg", alt: "Cursor Kigali Hackathon — DSC 7832", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-jcjcmbf0b-DSC_7837.jpg", alt: "Cursor Kigali Hackathon — DSC 7837", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-3o9ez92xe-DSC_7790.jpg", alt: "Cursor Kigali Hackathon — DSC 7790", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-jzrgvjzd9-DSC_7732.jpg", alt: "Cursor Kigali Hackathon — DSC 7732", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-kduguk1as-DSC_7755.jpg", alt: "Cursor Kigali Hackathon — DSC 7755", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-fjhkgs8mz-DSC_7831.jpg", alt: "Cursor Kigali Hackathon — DSC 7831", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-chnhif0j5-DSC_7839.jpg", alt: "Cursor Kigali Hackathon — DSC 7839", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-kj37j0z99-DSC_7825.jpg", alt: "Cursor Kigali Hackathon — DSC 7825", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-44x3jfv4x-DSC_7827_1.jpg", alt: "Cursor Kigali Hackathon — DSC 7827 1", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-8wfd5bot5-DSC_7823.jpg", alt: "Cursor Kigali Hackathon — DSC 7823", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-ww1yqtu2h-DSC_7743.jpg", alt: "Cursor Kigali Hackathon — DSC 7743", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-3tdt8mp9w-DSC_7831_1.jpg", alt: "Cursor Kigali Hackathon — DSC 7831 1", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-xmxugvofk-DSC_7809.jpg", alt: "Cursor Kigali Hackathon — DSC 7809", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-gqw0bqrcw-DSC_7810.jpg", alt: "Cursor Kigali Hackathon — DSC 7810", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-c662wwl2d-DSC_7798.jpg", alt: "Cursor Kigali Hackathon — DSC 7798", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-f66zvoap9-DSC_7813.jpg", alt: "Cursor Kigali Hackathon — DSC 7813", width: 1600, height: 1067 },
  { src: "https://r2.somapix.com/events/eXlxN5jouP9mNU7dWj4Y/photos/1783243480817-j7r9pzbyc-DSC_7822.jpg", alt: "Cursor Kigali Hackathon — DSC 7822", width: 1600, height: 1067 },
] as const satisfies readonly GalleryPhoto[]

export const FEATURED_HACKATHON_PHOTOS = HACKATHON_GALLERY_PHOTOS.slice(0, 8) as readonly GalleryPhoto[]
