#!/usr/bin/env node
/**
 * Sync hackathon gallery photos from SomaPix (Firestore).
 * Writes hackathon entries in src/lib/gallery-data.ts.
 * Cafe Cursor photos live separately in src/lib/cafe-gallery.ts.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const FIRESTORE_KEY = 'AIzaSyD_Itsj6_cNq77FTKWaoIybLa9UsfesbNI'
const EVENT_ID = 'eXlxN5jouP9mNU7dWj4Y'

function altFromFileName(fileName) {
  const base = fileName.replace(/\.[^.]+$/, '').replace(/[_-]+/g, ' ').trim()
  return `Cursor Kigali Hackathon — ${base}`
}

async function fetchSomaPixPhotos() {
  const response = await fetch(
    `https://firestore.googleapis.com/v1/projects/havityerp/databases/(default)/documents:runQuery?key=${FIRESTORE_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        structuredQuery: {
          from: [{ collectionId: 'photos' }],
          where: {
            fieldFilter: {
              field: { fieldPath: 'eventId' },
              op: 'EQUAL',
              value: { stringValue: EVENT_ID },
            },
          },
          limit: 500,
        },
      }),
    },
  )

  if (!response.ok) {
    throw new Error(`Firestore query failed: ${response.status}`)
  }

  const rows = await response.json()
  const photos = []

  for (const row of rows) {
    const doc = row.document
    if (!doc?.fields) continue

    const url = doc.fields.url?.stringValue
    const fileName = doc.fields.fileName?.stringValue
    if (!url || !fileName) continue

    photos.push({
      src: url,
      alt: altFromFileName(fileName),
      width: Number(doc.fields.width?.integerValue ?? 1600),
      height: Number(doc.fields.height?.integerValue ?? 1067),
    })
  }

  return photos
}

function toHackathonModule(photos) {
  const lines = photos.map((photo) => {
    const src = JSON.stringify(photo.src)
    const alt = JSON.stringify(photo.alt)
    return `  { src: ${src}, alt: ${alt}, width: ${photo.width}, height: ${photo.height} },`
  })

  return `// Generated by scripts/sync-gallery.mjs — do not edit by hand.
export type GalleryPhoto = {
  src: string
  alt: string
  width: number
  height: number
}

export const HACKATHON_GALLERY_PHOTOS = [
${lines.join('\n')}
] as const satisfies readonly GalleryPhoto[]

export const FEATURED_HACKATHON_PHOTOS = HACKATHON_GALLERY_PHOTOS.slice(0, 8) as readonly GalleryPhoto[]
`
}

async function main() {
  const photos = await fetchSomaPixPhotos()
  const outputPath = join(root, 'src/lib/gallery-data.ts')
  writeFileSync(outputPath, toHackathonModule(photos), 'utf8')
  console.log(`Wrote ${photos.length} hackathon photos to ${outputPath}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
